status = ["ci/circleci: test_e2e_start_service", "ci/circleci: test"]
delete_merged_branches = true
use_squash_merge = true
cut_body_after = "### Implementation details. How do you make this change?"
required_approvals=1
