# Marks all newly opened pull requests as drafts
name: Draft on Open
on:
  pull_request:
    types: [ opened ]

jobs:
  mark-as-draft:
    name: Mark as draft
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@latest
        with:
          token: ${{ secrets.GH_SA_TOKEN }}
