name: Trigger CircleCI Checks
on:
  pull_request:
    types: [ready_for_review]

jobs:
  trigger_circleci:
    runs-on: ubuntu-latest
    steps:
      - uses: voiceflow/trigger-circleci@latest
        with:
          circleci-token: ${{ secrets.CIRCLECI_TOKEN }}
